# ===========================
# Globale Parameter
# ===========================
strategy_path: "strategies.alpha_meme_strat:AlphaMemeStrategy"
config_path: "strategies.alpha_meme_strat:AlphaMemeStrategyConfig"

visualize: true
venue: "BINANCE"

# Instrumente
instruments:
  #- instrument_id: "BTCUSDT-PERP.BINANCE"
  #  bar_types: 
  #    - "BTCUSDT-PERP.BINANCE-15-MINUTE-LAST-EXTERNAL"
  #    - "BTCUSDT-PERP.BINANCE-5-MINUTE-LAST-EXTERNAL"
  #  trade_size_usdt: "100"
  #  test: 1

# Automatischer Import aus CSV:
# CSV Beispiel (Spaltenkopf 'symbol'): symbol,onboardDate
# Jede Zeile erzeugt instrument_id = <symbol>-PERP.<venue>
# bar_types = instrument_id + jede bar_type_endings Angabe
instruments_from_path:
  path: "../data/DATA_STORAGE/project_future_scraper/new_binance_perpetual_futures.csv"
  symbol_column: "symbol"
  instrument_suffix: "-PERP"
  bar_type_endings:
    - "-15-MINUTE-LAST-EXTERNAL"
  trade_size_usdt: "150"
  test: 2

# Backtest-Zeitraum
start_date: "2023-10-01T00:00:00Z"
end_date: "2025-10-31T00:00:00Z"

# Account/Venue-Parameter
starting_account_balance: "10000 USDT"
base_currency: "USDT"
account_type: "MARGIN"
oms_type: "NETTING"

# Risiko-Parameter (global)
trade_size_usdt: 1000
risk_percent: 0.01
max_leverage: 2
min_account_balance: 1000
close_positions_on_stop: [true]

# ===========================
# Strategie-spezifische Parameter
# ===========================

# RSI-Strategie
rsi_period: [10]
rsi_overbought: [0.75]
rsi_oversold: [0.25]
