# ===========================
# Globale Parameter
# ===========================
strategy_path: "strategies.beta_strat:RSISimpleStrategy"
config_path: "strategies.beta_strat:RSISimpleStrategyConfig"

visualize: true
load_qs: false
qs_bench: "BTC-USD"
venue: "BINANCE"

# Instrumente
instruments:
  - instrument_id: "BTCUSDT-PERP.BINANCE"
    bar_types: 
      - "BTCUSDT-PERP.BINANCE-15-MINUTE-LAST-EXTERNAL"
      - "BTCUSDT-PERP.BINANCE-5-MINUTE-LAST-EXTERNAL"
    trade_size_usdt: "100"
    test: 1

# Datenquellen (Standard + Custom)
data_sources:
  # Standard Bar-Daten: nutzt automatisch alle bar_types aus den Instrumenten
  - data_cls: "nautilus_trader.model.data:Bar"
    instrument_ids: all
    bar_types: from_instruments

  # Custom MetricsData f√ºr alle Instrumente (client_id wird automatisch gesetzt)
  - data_cls: "data.download.crypto_downloads.custom_class.metrics_data:MetricsData"
    instrument_ids: all

  - data_cls: "data.download.crypto_downloads.custom_class.lunar_data:LunarData"
    instrument_ids: all


# Backtest-Zeitraum
start_date: "2024-10-01T00:00:00Z"
end_date: "2024-10-31T00:00:00Z"

# Account/Venue-Parameter
starting_account_balance: "100000 USDT"
base_currency: "USDT"
account_type: "MARGIN"
oms_type: "NETTING"

# Risiko-Parameter (global)
trade_size_usdt: 1000
risk_percent: 0.01
max_leverage: 2
min_account_balance: 1000
close_positions_on_stop: [true]

# ===========================
# Strategie-spezifische Parameter
# ===========================

# RSI-Strategie
rsi_period: [10]
rsi_overbought: [0.75]
rsi_oversold: [0.25, 0.3]
