# Instrument
symbol: "SPY"
venue: "ARCA"
instrument_id: "SPY.ARCA"
bar_type: "SPY.ARCA-1-DAY-LAST-EXTERNAL"

# Backtest-Zeitraum
start_date: "2008-01-01T00:00:00Z"
end_date: "2024-12-30T23:59:59Z"

# Strategie-Parameter
slow_ema_period: [60]
fast_ema_period:  [10]
min_bars_under_fast_ema: [5]
min_bars_over_fast_ema: [9]


# Risk-Parameter
trade_size_usd: 1000
close_positions_on_stop: [true]
risk_percent: 0.01
max_leverage: 2
min_account_balance: 1000


# Account/Venue-Parameter
starting_account_balance: "100000 USD"
base_currency: "USD"
account_type: "MARGIN"
oms_type: "NETTING"
