## code f√ºr die dann aber wirklich nutzbar coin short strat

strategy_path: "strategies.short_tha_bich_strat:ShortThaBitchStrat"
config_path: "strategies.short_tha_bich_strat:ShortThaBitchStratConfig"

visualize: true
venue: "BYBIT"

# instruments:
#   - instrument_id: "BTCUSDT-LINEAR.BYBIT"
#     bar_types: 
#       - "BTCUSDT-LINEAR.BYBIT-15-MINUTE-LAST-EXTERNAL"
#     trade_size_usdt: "1"
    
instruments_from_path:
  path: "../data/DATA_STORAGE/project_future_scraper/new_bybit_linear_perpetual_futures.csv"
  symbol_column: "symbol"
  instrument_suffix: "-LINEAR"
  bar_type_endings:
    - "-15-MINUTE-LAST-EXTERNAL"
  trade_size_usdt: "150"
  test: 2

data_sources:
  - data_cls: "nautilus_trader.model.data:Bar"
    instrument_ids: all
    bar_types: from_instruments

  # - data_cls: "data.download.crypto_downloads.custom_class.bybit_metrics_data:BybitMetricsData"
  #   instrument_ids: all

start_date: "2025-01-01T00:00:00Z"
end_date: "2025-10-01T00:00:00Z"

starting_account_balance: "1000 USDT"
base_currency: "USDT"
account_type: "MARGIN"
oms_type: "NETTING"

close_positions_on_stop: true
min_account_balance: 1000

# exp_growth_atr_risk:
#   enabled: false
#   atr_period: 20
#   atr_multiple: 2.0
#   risk_percent: 0.04

log_growth_atr_risk:
  enabled: true
  atr_period: 50
  atr_multiple: 5.0
  risk_percent: 0.05 

# _______________________
# Strat params
# _______________________

only_execute_short: true
hold_profit_for_remaining_days: false
time_after_listing_close: 20
max_leverage: 1


# Entry System idea:
#_____________________

use_htf_ema_bias_filter:
  enabled: true
  ema_period: 300

use_macd_simple_reversion_system:
  enabled: true
  macd_fast_period: 20
  macd_slow_period: 32
  macd_signal_period: 16

use_rsi_simple_reversion_system:
  enabled: true
  usage_method: "condition" # or execution
  rsi_period: 20
  rsi_overbought: 0.6
  rsi_oversold: 0.3


# Entry System simple:
#_____________________
use_macd_exit_system:
  enabled: true
  macd_fast_exit_period: 30
  macd_slow_exit_period: 70
  macd_signal_exit_period: 25

  